<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Quản lý thiết bị | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><style>
.asset-thumb{width:46px;height:38px;object-fit:cover;border-radius:7px;border:1px solid var(--line);background:#eef6fc}.asset-placeholder{display:grid;width:46px;height:38px;place-items:center;border-radius:7px;color:#2875b7;background:#eaf3fb}.asset-placeholder svg{width:20px;height:20px;fill:none;stroke:currentColor;stroke-width:1.7}.asset-code{font-weight:700;color:var(--ink)}.asset-meta{display:block;margin-top:3px;color:var(--muted);font-size:10px}.asset-type{display:inline-flex;margin-top:4px;padding:3px 6px;border-radius:999px;font-size:9px;font-weight:700}.asset-type.fixed{color:#8a5a0a;background:#fff0ce}.asset-type.borrowable{color:#087f68;background:#e0f7ef}.status.available,.status.good{color:#0b8055;background:#e5f6ee}.status.maintenance,.status.fair{color:#a46b0b;background:#fff2d8}.status.unavailable,.status.damaged{color:#a45313;background:#ffeadb}.status.disposed,.status.broken{color:#a83d4f;background:#fbe4e8}.filter-bar .filter-group{flex-wrap:wrap}.filter-bar .form-control{min-width:150px}.filter-bar input.form-control{width:min(100%,360px)!important}.success-message{margin-bottom:10px;padding:9px 12px;border:1px solid #b9e9d2;border-radius:7px;color:#12704c;background:#edfbf3;font-size:11px}.asset-actions{display:flex;align-items:center;gap:4px}.asset-actions form{margin:0}.asset-actions .btn-action{margin-left:0}
</style></head>
<body class="${assetRole == 'mentor' ? 'mentor-page' : 'lab-manager-page'}">
<c:set var="activeMenu" value="assets" scope="request"/>
<div class="app-shell"><c:choose><c:when test="${assetRole == 'mentor'}"><%@ include file="../../mentor/includes/sidebar.jspf" %></c:when><c:otherwise><%@ include file="../includes/sidebar.jspf" %></c:otherwise></c:choose>
<main class="main-content"><header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Quản lý thiết bị</h1><p>Theo dõi từng sản phẩm và trạng thái tài sản trong phòng LAB</p></div></div><div class="topbar-actions"><div class="top-profile"><div class="avatar">${assetRole == 'mentor' ? 'ME' : 'LM'}</div><span><c:out value="${currentUser.fullName}"/></span></div></div></header>
<section class="content-area"><div class="content-heading"><div><p class="eyebrow">CỔNG QUẢN LÝ PHÒNG LAB</p><h2>Danh sách sản phẩm</h2></div><a class="primary-button" href="${assetBasePath}/new">+ Thêm thiết bị</a></div>
<c:if test="${param.created == '1'}"><div class="success-message">Đã tạo thiết bị và sinh mã riêng cho từng sản phẩm.</div></c:if>
<c:if test="${param.deleted == '1'}"><div class="success-message">Đã xóa sản phẩm và cập nhật lại số lượng thiết bị.</div></c:if>
<c:if test="${not empty message}"><div class="error-message"><c:out value="${message}"/></div></c:if>
<form class="filter-bar" method="get" action="${assetBasePath}"><div class="filter-group"><input class="form-control" type="search" name="keyword" value="<c:out value='${param.keyword}'/>" placeholder="Tìm theo mã, tên hoặc serial"><select class="form-control" name="status"><option value="">Tất cả trạng thái</option><option value="AVAILABLE" ${param.status == 'AVAILABLE' ? 'selected' : ''}>Sẵn sàng</option><option value="MAINTENANCE" ${param.status == 'MAINTENANCE' ? 'selected' : ''}>Đang bảo trì</option><option value="UNAVAILABLE" ${param.status == 'UNAVAILABLE' ? 'selected' : ''}>Không khả dụng</option><option value="DISPOSED" ${param.status == 'DISPOSED' ? 'selected' : ''}>Đã thanh lý</option></select><select class="form-control" name="condition"><option value="">Tất cả tình trạng</option><option value="GOOD" ${param.condition == 'GOOD' ? 'selected' : ''}>Tốt</option><option value="FAIR" ${param.condition == 'FAIR' ? 'selected' : ''}>Khá</option><option value="DAMAGED" ${param.condition == 'DAMAGED' ? 'selected' : ''}>Hư hỏng</option><option value="BROKEN" ${param.condition == 'BROKEN' ? 'selected' : ''}>Hỏng</option></select><button class="primary-button" type="submit">Lọc</button><a class="btn-secondary" href="${assetBasePath}">Đặt lại</a></div></form>
<article class="panel"><c:choose><c:when test="${empty assetItems}"><div class="empty-box"><div class="empty-box-icon"><svg><use href="#i-box"/></svg></div><h3>Chưa có sản phẩm</h3><p>Thêm thiết bị để hệ thống sinh mã riêng cho từng sản phẩm.</p></div></c:when><c:otherwise><div class="table-scroll"><table><thead><tr><th>Ảnh</th><th>Mã sản phẩm</th><th>Thiết bị</th><th>Dạng tài sản</th><th>Serial</th><th>Tình trạng</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody><c:forEach items="${assetItems}" var="item"><tr><td><c:choose><c:when test="${not empty item.imagePath}"><img class="asset-thumb" src="${pageContext.request.contextPath}${item.imagePath}" alt="Ảnh ${item.itemCode}"></c:when><c:otherwise><span class="asset-placeholder" aria-label="Chưa có ảnh"><svg><use href="#i-box"/></svg></span></c:otherwise></c:choose></td><td><span class="asset-code"><c:out value="${item.itemCode}"/></span></td><td><strong><c:out value="${item.assetName}"/></strong><small class="asset-meta"><c:out value="${item.categoryName}"/></small></td><td><span class="asset-type ${item.borrowable ? 'borrowable' : 'fixed'}"><c:out value="${item.borrowable ? 'Có thể mượn' : 'Cố định'}"/></span></td><td><c:out value="${empty item.serialNumber ? 'Chưa nhập' : item.serialNumber}"/></td><td><span class="status ${item.condition == 'GOOD' ? 'good' : item.condition == 'FAIR' ? 'fair' : item.condition == 'DAMAGED' ? 'damaged' : 'broken'}"><c:out value="${app:label(item.condition)}"/></span></td><td><span class="status ${item.status == 'AVAILABLE' ? 'available' : item.status == 'MAINTENANCE' ? 'maintenance' : item.status == 'UNAVAILABLE' ? 'unavailable' : 'disposed'}"><c:out value="${app:label(item.status)}"/></span></td><td><div class="asset-actions"><a class="btn-action" href="${assetBasePath}/${item.assetItemId}">Xem</a><a class="btn-action btn-action-primary" href="${assetBasePath}/${item.assetItemId}/edit">Sửa</a><form method="post" action="${assetBasePath}/${item.assetItemId}/delete" onsubmit="return confirm('Xóa sản phẩm này? Nếu sản phẩm đã có lịch sử sử dụng, hệ thống sẽ từ chối.');"><input type="hidden" name="csrfToken" value="${csrfToken}"><button class="btn-action btn-action-danger" type="submit">Xóa</button></form></div></td></tr></c:forEach></tbody></table></div><div class="table-footer"><span>Hiển thị ${assetItems.size()} sản phẩm</span></div></c:otherwise></c:choose></article>
</section></main></div>
</body></html>
