package fpt.swp391.labtoolequip.auth;

public enum Permission {
	DASHBOARD_ADMIN, DASHBOARD_MENTOR, DASHBOARD_LAB_MANAGER, DASHBOARD_INTERN, USER_MANAGE, INTERN_LIST_VIEW, INTERN_LIST_EDIT, INTERN_LIST_REVIEW, ASSET_VIEW, ASSET_MANAGE, ASSET_USAGE_VIEW, ASSET_USAGE_BORROW, ASSET_USAGE_RETURN, INCIDENT_VIEW, INCIDENT_REPORT, INCIDENT_REVIEW, INCIDENT_RESOLVE, RESPONSIBILITY_VIEW, RESPONSIBILITY_ASSESS, MAINTENANCE_VIEW, MAINTENANCE_REQUEST, MAINTENANCE_PROCESS, DISPOSAL_VIEW, DISPOSAL_REQUEST, DISPOSAL_REVIEW, DISPOSAL_COMPLETE, PASSWORD_RESET_REQUEST, PASSWORD_RESET_REVIEW, PASSWORD_RESET_ISSUE, PASSWORD_CHANGE
}
