<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Mentor Dashboard | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"></head>
<body>
<div class="app-shell"><c:set var="activeMenu" value="dashboard"/><%@ include file="includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Open navigation" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Mentor Dashboard</h1><p>Manage the intern list and lab assets</p></div></div><div class="top-profile"><div class="avatar">ME</div><span><c:out value="${currentUser.fullName}"/></span></div></header>
    <section class="content-area"><div class="content-heading"><div><p class="eyebrow">MENTOR PORTAL</p><h2>Intern list overview</h2></div><a class="primary-button" href="${pageContext.request.contextPath}/mentor/interns">Manage intern lists</a></div>
        <section class="stats-grid"><article class="stat-card stat-green"><div class="stat-icon"><svg><use href="#i-users"/></svg></div><div><strong><c:out value="${approvedRequests.size()}"/></strong><span>Approved lists</span><small>One list per semester</small></div></article><article class="stat-card stat-gold"><div class="stat-icon"><svg><use href="#i-clipboard"/></svg></div><div><strong>Pending</strong><span>Approval workflow</span><small>Admin decides once</small></div></article><article class="stat-card stat-blue"><div class="stat-icon"><svg><use href="#i-box"/></svg></div><div><strong>Lab</strong><span>Single managed room</span><small>No slots or schedules</small></div></article></section>
        <article class="panel"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-users"/></svg></span><h3>Approved intern lists</h3></div><a href="${pageContext.request.contextPath}/mentor/interns">View all</a></header><div class="table-scroll"><table><thead><tr><th>List</th><th>Semester</th><th>Interns</th><th>Status</th><th></th></tr></thead><tbody><c:choose><c:when test="${empty approvedRequests}"><tr><td colspan="5">No approved intern list yet.</td></tr></c:when><c:otherwise><c:forEach var="internList" items="${approvedRequests}"><tr><td><c:out value="${internList.groupName}"/></td><td><c:out value="${internList.semesterCode}"/></td><td><c:out value="${internList.studentCount}"/></td><td><span class="status returned">APPROVED</span></td><td><a href="${pageContext.request.contextPath}/mentor/interns/view?id=${internList.requestId}">View</a></td></tr></c:forEach></c:otherwise></c:choose></tbody></table></div></article>
    </section>
</main></div>
</body></html>
