<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Thanh lý #${disposal.disposalId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"></head>
<body class="lab-manager-page">
<c:set var="activeMenu" value="disposals" scope="request"/>
<div class="app-shell">
    <%@ include file="../includes/sidebar.jspf" %>
    <main class="main-content">
        <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Chi tiết thanh lý</h1><p>Vòng đời thiết bị và hồ sơ thanh lý</p></div></div><div class="topbar-actions"><a class="btn-secondary" href="${pageContext.request.contextPath}/lab-manager/disposals">Quay lại danh sách thanh lý</a></div></header>
        <section class="content-area">
            <div class="content-heading"><div><p class="eyebrow">THANH LÝ #DSP-${disposal.disposalId}</p><h2><c:out value="${disposal.assetName}"/></h2></div><span class="status ${disposal.status == 'PENDING' || disposal.status == 'APPROVED' ? 'review' : disposal.status == 'COMPLETED' ? 'returned' : 'open'}"><c:out value="${app:label(disposal.status)}"/></span></div>
            <c:if test="${not empty message}"><div class="error-message"><c:out value="${message}"/></div></c:if>
            <dl class="panel detail-grid"><div class="detail-item"><dt>Thiết bị</dt><dd><c:out value="${disposal.assetCode}"/><c:if test="${not empty disposal.assetItemTag}"><br><small><c:out value="${disposal.assetItemTag}"/></small></c:if></dd></div><div class="detail-item"><dt>Tình trạng thiết bị</dt><dd><c:out value="${app:label(disposal.assetCondition)}"/></dd></div><div class="detail-item"><dt>Số lượng thanh lý</dt><dd><c:out value="${disposal.quantity}"/></dd></div><div class="detail-item"><dt>Người yêu cầu</dt><dd><c:out value="${disposal.requesterName}"/></dd></div><div class="detail-item"><dt>Thời gian yêu cầu</dt><dd><c:out value="${app:dateTime(disposal.requestedAt)}"/></dd></div><div class="detail-item"><dt>Người duyệt</dt><dd><c:out value="${empty disposal.approverName ? 'Chưa duyệt' : disposal.approverName}"/></dd></div><div class="detail-item"><dt>Thời gian duyệt</dt><dd><c:out value="${app:dateTime(disposal.approvedAt)}"/></dd></div><div class="detail-item"><dt>Hoàn tất lúc</dt><dd><c:out value="${app:dateTime(disposal.completedAt)}"/></dd></div><div class="detail-item wide"><dt>Lý do thanh lý</dt><dd><c:out value="${disposal.reason}"/></dd></div><div class="detail-item wide"><dt>Ghi chú duyệt</dt><dd><c:out value="${empty disposal.approvalNote ? 'Không có ghi chú.' : disposal.approvalNote}"/></dd></div><div class="detail-item wide"><dt>Kết quả thanh lý</dt><dd><c:out value="${empty disposal.completionNote ? 'Chưa có kết quả thanh lý.' : disposal.completionNote}"/></dd></div></dl>
            <c:if test="${disposal.status == 'PENDING'}"><article class="panel"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-list"/></svg></span><h3>Duyệt yêu cầu thanh lý</h3></div></header><form method="post" action="${pageContext.request.contextPath}/lab-manager/disposals/${disposal.disposalId}"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="disposalId" value="${disposal.disposalId}"><div class="form-grid"><div class="form-group full-width"><label for="reviewNote">Ghi chú duyệt</label><textarea class="form-control" id="reviewNote" name="reviewNote" maxlength="2000" placeholder="Ghi chú tùy chọn khi duyệt hoặc từ chối"></textarea></div><div class="form-group full-width form-actions"><button class="btn-danger" name="action" value="reject" onclick="return confirm('Từ chối yêu cầu thanh lý này?');">Từ chối</button><button class="primary-button" name="action" value="approve" onclick="return confirm('Duyệt yêu cầu thanh lý này?');">Duyệt yêu cầu</button></div></div></form></article></c:if>
            <c:if test="${disposal.status == 'APPROVED'}"><article class="panel"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-trash"/></svg></span><h3>Hoàn tất thanh lý</h3></div></header><form method="post" action="${pageContext.request.contextPath}/lab-manager/disposals/${disposal.disposalId}"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="disposalId" value="${disposal.disposalId}"><div class="form-grid"><div class="form-group full-width"><label for="completionNote">Kết quả thanh lý</label><textarea class="form-control" id="completionNote" name="completionNote" maxlength="2000" required placeholder="Thông tin hoàn tất hoặc kết quả thanh lý"></textarea></div><div class="form-group full-width form-actions"><button class="primary-button" name="action" value="complete" onclick="return confirm('Hoàn tất thanh lý? Thiết bị sẽ không còn được sử dụng hoặc mượn.');">Hoàn tất thanh lý</button></div></div></form></article></c:if>
        </section>
    </main>
</div>
</body>
</html>
