<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Tạo hồ sơ thanh lý | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"></head>
<body class="lab-manager-page"><c:set var="activeMenu" value="disposals" scope="request"/><div class="app-shell"><%@ include file="../includes/sidebar.jspf" %><main class="main-content">
<header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng"><svg><use href="#i-menu"/></svg></button><div><h1>Tạo hồ sơ thanh lý</h1><p>Chỉ Lab Manager được lập và xử lý hồ sơ thanh lý.</p></div></div><div class="topbar-actions"><a class="btn-secondary" href="${pageContext.request.contextPath}/lab-manager/disposals">Quay lại danh sách</a></div></header>
<section class="content-area"><c:if test="${not empty message}"><div class="error-message"><c:out value="${message}"/></div></c:if><article class="panel"><form class="form-grid" method="post" action="${pageContext.request.contextPath}/lab-manager/disposals"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="create">
<div class="form-group full-width"><label>Loại tài sản *</label><select class="form-control" id="targetType"><option value="">-- Chọn loại --</option><option value="quantity">Tài sản theo số lượng</option><option value="item">Sản phẩm theo mã riêng</option></select></div>
<div class="form-group full-width" id="quantityTarget" hidden><label>Tài sản theo số lượng *</label><select class="form-control" name="assetId"><option value="">-- Chọn tài sản --</option><c:forEach items="${quantityAssets}" var="asset"><option value="${asset.assetId}"><c:out value="${asset.assetName}"/> (<c:out value="${asset.assetCode}"/>)</option></c:forEach></select></div>
<div class="form-group full-width" id="itemTarget" hidden><label>Sản phẩm theo mã riêng *</label><select class="form-control" name="assetItemId"><option value="">-- Chọn sản phẩm --</option><c:forEach items="${assetItems}" var="item"><option value="${item.assetItemId}"><c:out value="${item.assetName}"/> · <c:out value="${item.itemTag}"/></option></c:forEach></select></div>
<div class="form-group full-width"><label>Lý do thanh lý *</label><textarea class="form-control" name="reason" rows="4" maxlength="2000" required placeholder="Nêu kết quả đánh giá, lý do không thể tiếp tục sử dụng hoặc sửa chữa."></textarea></div><div class="form-group full-width form-actions"><button class="primary-button" type="submit">Tạo hồ sơ</button><a class="btn-secondary" href="${pageContext.request.contextPath}/lab-manager/disposals">Hủy</a></div></form></article></section>
</main></div><script>document.addEventListener('DOMContentLoaded',()=>{const type=document.getElementById('targetType'),quantity=document.getElementById('quantityTarget'),item=document.getElementById('itemTarget');type.addEventListener('change',()=>{quantity.hidden=type.value!=='quantity';item.hidden=type.value!=='item';});});</script></body></html>
