<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Intern List #${labRequest.requestId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-lab-requests.css"></head>
<body>
<div class="app-shell"><c:set var="activeMenu" value="labRequests"/><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Open navigation" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Intern List #<c:out value="${labRequest.requestId}"/></h1><p>Semester intern access list</p></div></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2><c:out value="${labRequest.groupName}"/></h2><p><c:out value="${labRequest.semesterCode}"/> — <c:out value="${labRequest.semesterName}"/></p></div><div class="row-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/mentor/interns">Back</a><c:if test="${labRequest.status == 'PENDING'}"><a class="primary-button" href="${pageContext.request.contextPath}/mentor/interns/edit?id=${labRequest.requestId}">Edit list</a></c:if></div></div>
        <c:if test="${param.created == '1'}"><div class="notice">Intern list submitted successfully.</div></c:if><c:if test="${param.updated == '1'}"><div class="notice">Intern list updated successfully.</div></c:if>
        <div class="detail-grid"><div class="detail-item"><span>Status</span><strong><span class="request-status status-${labRequest.status}"><c:out value="${labRequest.status}"/></span></strong></div><div class="detail-item"><span>Semester</span><strong><c:out value="${labRequest.semesterCode}"/></strong></div><div class="detail-item"><span>Interns</span><strong><c:out value="${labRequest.studentCount}"/></strong></div><div class="detail-item"><span>Submitted</span><strong><c:out value="${labRequest.createdAt}"/></strong></div></div>
        <section class="request-card detail-section"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-users"/></svg></span><h3>Intern access list</h3></div></header><div class="request-table-wrap"><table class="detail-table"><thead><tr><th>#</th><th>Intern code</th><th>Full name</th><th>Gmail</th><th>Cohort</th></tr></thead><tbody><c:forEach var="intern" items="${labRequest.students}" varStatus="loop"><tr><td>${loop.count}</td><td><c:out value="${intern.studentCode}"/></td><td><c:out value="${intern.fullName}"/></td><td><c:out value="${intern.email}"/></td><td><c:out value="${intern.cohort}"/></td></tr></c:forEach></tbody></table></div></section>
        <div class="approval-note"><h3>Mentor note</h3><p><c:out value="${labRequest.requestNote}" default="No note provided."/></p></div><c:if test="${labRequest.status != 'PENDING'}"><div class="approval-note"><h3>Admin decision note</h3><p><c:out value="${labRequest.approvalNote}" default="No decision note provided."/></p></div></c:if>
    </section>
</main></div>
</body></html>
