<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Review Intern List #${labRequest.requestId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-lab-requests.css"></head>
<body>
<c:set var="activeMenu" value="labRequests" scope="request"/><div class="app-shell"><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Open navigation" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Review Intern List #<c:out value="${labRequest.requestId}"/></h1><p>Approve and manage the complete semester list</p></div></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2><c:out value="${labRequest.groupName}"/></h2><p>Submitted by <c:out value="${labRequest.mentorName}"/> · <c:out value="${labRequest.mentorEmail}"/> · <c:out value="${labRequest.semesterCode}"/></p></div><div class="row-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/admin/interns">Back to queue</a><a class="action-link" href="${pageContext.request.contextPath}/admin/interns/edit?id=${labRequest.requestId}">Edit</a><form method="post" action="${pageContext.request.contextPath}/admin/interns/delete" onsubmit="return confirm('Delete this intern list and orphaned intern accounts?');"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${labRequest.requestId}"><button class="danger-button" type="submit">Delete</button></form></div></div>
        <c:if test="${param.decided == 'APPROVED'}"><div class="notice">Intern list approved. All listed intern accounts are active.</div></c:if><c:if test="${param.decided == 'REJECTED'}"><div class="notice">Intern list rejected. No intern membership was created.</div></c:if><c:if test="${param.updated == '1'}"><div class="notice">Intern list updated successfully.</div></c:if><c:if test="${not empty decisionError}"><div class="notice error"><c:out value="${decisionError}"/></div></c:if>
        <div class="detail-grid"><div class="detail-item"><span>Status</span><strong><span class="request-status status-${labRequest.status}"><c:out value="${labRequest.status}"/></span></strong></div><div class="detail-item"><span>Semester</span><strong><c:out value="${labRequest.semesterCode}"/></strong></div><div class="detail-item"><span>Interns</span><strong><c:out value="${labRequest.studentCount}"/></strong></div><div class="detail-item"><span>Submitted</span><strong><c:out value="${labRequest.createdAt}"/></strong></div></div>
        <section class="request-card detail-section"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-users"/></svg></span><h3>Submitted intern list</h3></div></header><div class="request-table-wrap"><table class="detail-table"><thead><tr><th>#</th><th>Intern code</th><th>Full name</th><th>Gmail</th><th>Cohort</th><th>Account</th></tr></thead><tbody><c:forEach var="intern" items="${labRequest.students}" varStatus="loop"><tr><td>${loop.count}</td><td><c:out value="${intern.studentCode}"/></td><td><c:out value="${intern.fullName}"/></td><td><c:out value="${intern.email}"/></td><td><c:out value="${intern.cohort}"/></td><td><c:choose><c:when test="${not empty intern.studentId}"><span class="badge badge-green">ACTIVE</span></c:when><c:otherwise><span class="badge badge-gray">PENDING</span></c:otherwise></c:choose></td></tr></c:forEach></tbody></table></div></section>
        <div class="approval-note"><h3>Mentor note</h3><p><c:out value="${labRequest.requestNote}" default="No note provided."/></p></div><c:choose><c:when test="${labRequest.status == 'PENDING'}"><form class="form-section detail-section" method="post" action="${pageContext.request.contextPath}/admin/interns/decision"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${labRequest.requestId}"><label class="field"><span>Decision note</span><textarea name="approvalNote" maxlength="2000" placeholder="Optional note for the Mentor..."></textarea></label><div class="form-actions"><button class="danger-button" type="submit" name="decision" value="REJECTED" onclick="return confirm('Reject this intern list?');">Reject list</button><button class="primary-button" type="submit" name="decision" value="APPROVED" onclick="return confirm('Approve this list and activate all interns?');">Approve list</button></div></form></c:when><c:otherwise><div class="approval-note"><h3>Admin decision note</h3><p><c:out value="${labRequest.approvalNote}" default="No decision note provided."/></p></div></c:otherwise></c:choose>
    </section>
</main></div>
</body></html>
