<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Edit Intern List | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-lab-requests.css"></head>
<body>
<c:set var="activeMenu" value="labRequests" scope="request"/><div class="app-shell"><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Open navigation" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Edit Intern List</h1><p>Admin can update this list in any status</p></div></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2>Update intern list</h2><p>Admin changes to an approved list are synchronized with its intern memberships.</p></div><a class="secondary-button" href="${pageContext.request.contextPath}/admin/interns">Back to list</a></div>
        <c:if test="${not empty errors}"><ul class="error-list"><c:forEach var="error" items="${errors}"><li><c:out value="${error}"/></li></c:forEach></ul></c:if>
        <form class="form-shell" method="post" action="${pageContext.request.contextPath}/admin/interns/edit"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${labRequest.requestId}">
            <section class="form-section"><h3>List information</h3><div class="form-grid"><label class="field"><span>Semester *</span><select name="semesterId" required><option value="">Select semester</option><c:forEach var="semester" items="${semesters}"><option value="${semester.semesterId}" ${labRequest.semesterId == semester.semesterId ? 'selected' : ''}><c:out value="${semester.code}"/> — <c:out value="${semester.name}"/></option></c:forEach></select></label><label class="field"><span>List name *</span><input type="text" name="groupName" maxlength="100" value="<c:out value='${labRequest.groupName}'/>" required></label><label class="field wide"><span>Mentor note</span><textarea name="requestNote"><c:out value="${labRequest.requestNote}"/></textarea></label></div></section>
            <section class="form-section"><div class="section-tools"><div><h3>Interns</h3><span class="section-label">Intern code, full name, Gmail and cohort</span></div><button class="secondary-button" id="addIntern" type="button">Add intern row</button></div><div class="scroll-box"><table class="student-editor"><thead><tr><th>Intern code</th><th>Full name</th><th>Gmail</th><th>Cohort</th><th></th></tr></thead><tbody id="internRows"><c:forEach var="intern" items="${labRequest.students}"><tr><td><input name="internCode" value="<c:out value='${intern.studentCode}'/>" required></td><td><input name="internName" value="<c:out value='${intern.fullName}'/>" required></td><td><input type="email" name="internEmail" value="<c:out value='${intern.email}'/>" required></td><td><input name="cohort" value="<c:out value='${intern.cohort}'/>" required></td><td><button class="danger-button remove-intern" type="button">Remove</button></td></tr></c:forEach></tbody></table></div></section>
            <div class="form-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/admin/interns">Cancel</a><button class="primary-button" type="submit">Save changes</button></div>
        </form>
    </section>
</main></div>
<template id="internRowTemplate"><tr><td><input name="internCode" required></td><td><input name="internName" required></td><td><input type="email" name="internEmail" required></td><td><input name="cohort" required></td><td><button class="danger-button remove-intern" type="button">Remove</button></td></tr></template><script>const rows=document.getElementById('internRows');document.getElementById('addIntern').addEventListener('click',()=>rows.append(document.getElementById('internRowTemplate').content.cloneNode(true)));rows.addEventListener('click',event=>{if(event.target.classList.contains('remove-intern'))event.target.closest('tr').remove();});</script>
</body></html>
