<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="fn" uri="jakarta.tags.functions"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Manage Intern Lists | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-lab-requests.css"></head>
<body>
<c:set var="activeMenu" value="labRequests" scope="request"/><div class="app-shell"><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Open navigation" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Manage Intern Lists</h1><p>Review and manage the single semester list sent by the Mentor</p></div></div><div class="top-profile"><div class="avatar">AD</div><span><c:out value="${currentUser.fullName}"/></span></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2>Intern list directory</h2><p>Admin can view, edit or delete intern lists in any status. Deleting a list also removes orphaned intern accounts.</p></div></div>
        <c:if test="${param.deleted == '1'}"><div class="notice">Intern list deleted successfully.</div></c:if><c:if test="${param.error == 'delete'}"><div class="notice error">Could not delete this intern list.</div></c:if>
        <div class="request-card"><form class="filter-bar" method="get" action="${pageContext.request.contextPath}/admin/interns"><input type="search" name="keyword" value="${fn:escapeXml(keyword)}" placeholder="Search list, Mentor or semester..." aria-label="Search lists"><select name="status" aria-label="Status"><option value="">All statuses</option><option value="PENDING" ${selectedStatus == 'PENDING' ? 'selected' : ''}>Pending</option><option value="APPROVED" ${selectedStatus == 'APPROVED' ? 'selected' : ''}>Approved</option><option value="REJECTED" ${selectedStatus == 'REJECTED' ? 'selected' : ''}>Rejected</option></select><select name="semesterId" aria-label="Semester"><option value="">All open semesters</option><c:forEach var="semester" items="${semesters}"><option value="${semester.semesterId}" ${selectedSemesterId == semester.semesterId ? 'selected' : ''}><c:out value="${semester.code}"/> — <c:out value="${semester.name}"/></option></c:forEach></select><div class="filter-actions"><button class="secondary-button" type="submit">Filter</button><a class="secondary-button" href="${pageContext.request.contextPath}/admin/interns">Clear</a></div></form>
            <c:choose><c:when test="${empty requests}"><div class="empty-state"><p>No intern lists found.</p></div></c:when><c:otherwise><div class="request-table-wrap"><table class="request-table"><thead><tr><th>ID</th><th>List / Semester</th><th>Mentor</th><th>Interns</th><th>Status</th><th>Actions</th></tr></thead><tbody><c:forEach var="internList" items="${requests}"><tr><td>#<c:out value="${internList.requestId}"/></td><td class="group-cell"><strong><c:out value="${internList.groupName}"/></strong><small><c:out value="${internList.semesterCode}"/> · <c:out value="${internList.semesterName}"/></small></td><td class="group-cell"><strong><c:out value="${internList.mentorName}"/></strong><small><c:out value="${internList.mentorEmail}"/></small></td><td><c:out value="${internList.studentCount}"/></td><td><span class="request-status status-${internList.status}"><c:out value="${internList.status}"/></span></td><td><div class="row-actions"><a class="action-link" href="${pageContext.request.contextPath}/admin/interns/view?id=${internList.requestId}">View</a><a class="action-link" href="${pageContext.request.contextPath}/admin/interns/edit?id=${internList.requestId}">Edit</a><form method="post" action="${pageContext.request.contextPath}/admin/interns/delete" onsubmit="return confirm('Delete this intern list and orphaned intern accounts?');"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${internList.requestId}"><button class="danger-button" type="submit">Delete</button></form></div></td></tr></c:forEach></tbody></table></div></c:otherwise></c:choose>
        </div>
    </section>
</main></div>
</body></html>
