<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Duyệt danh sách thực tập sinh #${internList.requestId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-intern-lists.css"></head>
<body class="admin-page">
<c:set var="activeMenu" value="internLists" scope="request"/><div class="app-shell"><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Duyệt danh sách thực tập sinh #<c:out value="${internList.requestId}"/></h1><p>Phê duyệt và quản lý danh sách đầy đủ của học kỳ</p></div></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2><c:out value="${internList.groupName}"/></h2><p>Người gửi <c:out value="${internList.mentorName}"/> · <c:out value="${internList.mentorEmail}"/> · <c:out value="${internList.semesterCode}"/></p></div><div class="row-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/admin/interns">Quay lại hàng chờ</a><a class="action-link" href="${pageContext.request.contextPath}/admin/interns/edit?id=${internList.requestId}">Sửa</a><form method="post" action="${pageContext.request.contextPath}/admin/interns/delete" onsubmit="return confirm('Xóa danh sách này, lịch sử hoạt động và các tài khoản thực tập sinh không còn liên kết?');"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${internList.requestId}"><button class="danger-button" type="submit">Xóa</button></form></div></div>
        <c:if test="${param.decided == 'APPROVED'}"><div class="notice">Đã phê duyệt danh sách. Tất cả tài khoản thực tập sinh trong danh sách đã hoạt động.</div></c:if><c:if test="${param.decided == 'REJECTED'}"><div class="notice">Đã từ chối danh sách. Không có quyền thực tập sinh nào được tạo.</div></c:if><c:if test="${param.updated == '1'}"><div class="notice">Đã cập nhật danh sách thực tập sinh.</div></c:if><c:if test="${not empty decisionError}"><div class="notice error"><c:out value="${decisionError}"/></div></c:if>
        <div class="detail-grid"><div class="detail-item"><span>Trạng thái</span><strong><span class="request-status status-${internList.status}"><c:out value="${app:label(internList.status)}"/></span></strong></div><div class="detail-item"><span>Học kỳ</span><strong><c:out value="${internList.semesterCode}"/></strong></div><div class="detail-item"><span>Thực tập sinh</span><strong><c:out value="${internList.studentCount}"/></strong></div><div class="detail-item"><span>Ngày gửi</span><strong><c:out value="${app:dateTime(internList.createdAt)}"/></strong></div></div>
        <section class="request-card detail-section"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-users"/></svg></span><h3>Danh sách thực tập sinh đã gửi</h3></div></header><div class="request-table-wrap"><table class="detail-table"><thead><tr><th>#</th><th>Mã thực tập sinh</th><th>Họ và tên</th><th>Địa chỉ email</th><th>Khóa</th><th>Tài khoản</th></tr></thead><tbody><c:forEach var="intern" items="${internList.students}" varStatus="loop"><tr><td>${loop.count}</td><td><c:out value="${intern.studentCode}"/></td><td><c:out value="${intern.fullName}"/></td><td><c:out value="${intern.email}"/></td><td><c:out value="${intern.cohort}"/></td><td><c:choose><c:when test="${not empty intern.studentId}"><span class="badge badge-green">Đang hoạt động</span></c:when><c:otherwise><span class="badge badge-gray">Chờ duyệt</span></c:otherwise></c:choose></td></tr></c:forEach></tbody></table></div></section>
        <div class="approval-note"><h3>Ghi chú của người hướng dẫn</h3><p><c:out value="${internList.requestNote}" default="Không có ghi chú."/></p></div><c:choose><c:when test="${internList.status == 'PENDING'}"><form class="form-section detail-section" method="post" action="${pageContext.request.contextPath}/admin/interns/decision"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="id" value="${internList.requestId}"><label class="field"><span>Ghi chú quyết định</span><textarea name="approvalNote" maxlength="2000" placeholder="Ghi chú tùy chọn cho người hướng dẫn..."></textarea></label><div class="form-actions"><button class="danger-button" type="submit" name="decision" value="REJECTED" onclick="return confirm('Từ chối danh sách thực tập sinh này?');">Từ chối danh sách</button><button class="primary-button" type="submit" name="decision" value="APPROVED" onclick="return confirm('Phê duyệt danh sách và kích hoạt tất cả thực tập sinh?');">Phê duyệt danh sách</button></div></form></c:when><c:otherwise><div class="approval-note"><h3>Ghi chú quyết định của quản trị viên</h3><p><c:out value="${internList.approvalNote}" default="Không có ghi chú quyết định."/></p></div></c:otherwise></c:choose>
    </section>
</main></div>
</body></html>
