<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8" %>
<%@ taglib prefix="c" uri="jakarta.tags.core" %>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld" %>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Sự cố #INC-${incident.incidentId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"></head>
<body class="mentor-page">
<c:set var="activeMenu" value="incidents" scope="request"/>
<div class="app-shell">
    <%@ include file="../includes/sidebar.jspf" %>
    <main class="main-content">
        <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng"><svg><use href="#i-menu"/></svg></button><div><h1>Sự cố #INC-${incident.incidentId}</h1><p>Duyệt báo cáo Intern hoặc theo dõi kết quả xử lý kỹ thuật</p></div></div><div class="topbar-actions"><a class="btn-secondary" href="${pageContext.request.contextPath}/mentor/incidents">‹ Quay lại danh sách</a></div></header>
        <section class="content-area">
            <c:if test="${not empty message}"><div class="error-message"><c:out value="${message}"/></div></c:if>
            <c:if test="${param.forwarded == '1'}"><div class="success-message">Đã chuyển sự cố đến Lab Manager để điều tra.</div></c:if>
            <div class="content-heading"><div><p class="eyebrow">BÁO CÁO SỰ CỐ</p><h2><c:out value="${incident.assetName}"/></h2></div><span class="status ${incident.status == 'REPORTED' || incident.status == 'OPEN' ? 'open' : incident.status == 'RESOLVED' || incident.status == 'CLOSED' ? 'returned' : 'review'}"><c:out value="${app:label(incident.status)}"/></span></div>
            <dl class="panel detail-grid"><div class="detail-item"><dt>Thiết bị</dt><dd><c:out value="${incident.assetCode}"/><c:if test="${not empty incident.assetItemCode}"><br><small><c:out value="${incident.assetItemCode}"/></small></c:if></dd></div><div class="detail-item"><dt>Người báo cáo</dt><dd><c:out value="${incident.reporterName}"/> · <c:out value="${app:label(incident.reporterRole)}"/></dd></div><div class="detail-item"><dt>Thực tập sinh liên quan</dt><dd><c:out value="${empty incident.internName ? '—' : incident.internName}"/></dd></div><div class="detail-item"><dt>Loại / mức độ</dt><dd><c:out value="${app:label(incident.incidentType)}"/> · <c:out value="${app:label(incident.severity)}"/></dd></div><div class="detail-item"><dt>Thời điểm xảy ra</dt><dd><c:out value="${app:dateTime(incident.occurredAt)}"/></dd></div><div class="detail-item"><dt>Thời điểm báo</dt><dd><c:out value="${app:dateTime(incident.reportedAt)}"/></dd></div><div class="detail-item wide"><dt>Mô tả đã gửi</dt><dd><c:out value="${incident.description}"/></dd></div><c:if test="${not empty incident.mentorReviewNote}"><div class="detail-item wide"><dt>Ghi chú Mentor</dt><dd><c:out value="${incident.mentorReviewNote}"/></dd></div><div class="detail-item"><dt>Mentor duyệt</dt><dd><c:out value="${empty incident.reviewerName ? '—' : incident.reviewerName}"/></dd></div><div class="detail-item"><dt>Thời điểm chuyển tiếp</dt><dd><c:out value="${app:dateTime(incident.forwardedAt)}"/></dd></div></c:if><c:if test="${not empty incident.technicalCause}"><div class="detail-item"><dt>Nguyên nhân kỹ thuật</dt><dd><c:out value="${app:label(incident.technicalCause)}"/></dd></div><div class="detail-item"><dt>Mức độ kỹ thuật</dt><dd><c:out value="${app:label(incident.technicalSeverity)}"/></dd></div><div class="detail-item"><dt>Khả năng sửa chữa</dt><dd><c:out value="${app:label(incident.repairability)}"/></dd></div><div class="detail-item"><dt>Hướng xử lý</dt><dd><c:out value="${app:label(incident.recommendedAction)}"/></dd></div><div class="detail-item wide"><dt>Ghi chú kỹ thuật</dt><dd><c:out value="${incident.technicalNote}"/></dd></div></c:if><div class="detail-item wide"><dt>Kết quả xử lý</dt><dd><c:out value="${empty incident.handlingResult ? 'Chưa có kết quả xử lý.' : incident.handlingResult}"/></dd></div></dl>
            <c:if test="${incident.status == 'REPORTED' && incident.reporterRole == 'INTERN' && permissions.allows('INCIDENT_REVIEW')}"><article class="panel"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-alert"/></svg></span><h3>Duyệt và chuyển Lab Manager</h3></div></header><form class="form-grid" method="post" action="${pageContext.request.contextPath}/mentor/incidents/${incident.incidentId}"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="forward"><input type="hidden" name="incidentId" value="${incident.incidentId}"><div class="form-group full-width"><label for="mentorReviewNote">Ghi chú duyệt *</label><textarea class="form-control" id="mentorReviewNote" name="mentorReviewNote" rows="4" maxlength="2000" required placeholder="Bổ sung thông tin giám sát, xác nhận bối cảnh hoặc điểm cần Lab Manager kiểm tra."><c:out value="${param.mentorReviewNote}"/></textarea><small>Ghi chú này không phải kết luận trách nhiệm.</small></div><div class="form-group full-width form-actions"><button class="primary-button" type="submit">Chuyển Lab Manager điều tra</button></div></form></article></c:if>
            <c:if test="${incident.status == 'OPEN'}"><p class="error-message">Bản ghi lịch sử OPEN chỉ có thể xem. Tạo báo cáo mới theo quy trình hiện hành khi cần.</p></c:if>
        </section>
    </main>
</div>
</body>
</html>
