<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Tạo yêu cầu thanh lý | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"></head>
<body class="mentor-page">
<c:set var="activeMenu" value="disposals" scope="request"/>
<div class="app-shell">
    <%@ include file="../includes/sidebar.jspf" %>
    <main class="main-content">
        <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Tạo yêu cầu thanh lý</h1><p>Đề xuất xử lý tài sản không còn an toàn hoặc phù hợp sử dụng</p></div></div><div class="topbar-actions"><a class="btn-secondary" href="${pageContext.request.contextPath}/mentor/disposals">Quay lại danh sách</a></div></header>
        <section class="content-area">
            <div class="content-heading"><div><p class="eyebrow">CỔNG NGƯỜI HƯỚNG DẪN</p><h2>Chọn tài sản cần thanh lý</h2></div></div>
            <c:if test="${not empty message}"><p class="error-message"><c:out value="${message}"/></p></c:if>
            <c:if test="${empty quantityAssets and empty assetItems}"><article class="panel"><div class="empty-box"><div class="empty-box-icon"><svg><use href="#i-trash"/></svg></div><h3>Không có tài sản đủ điều kiện</h3><p>Hiện chưa có tài sản phù hợp để tạo yêu cầu thanh lý.</p></div></article></c:if>
            <c:if test="${not empty quantityAssets}"><article class="panel"><header class="panel-header"><div class="panel-title"><h3>Tài sản quản lý theo số lượng</h3></div></header><form class="form-grid" method="post"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="create"><div class="form-group full-width"><label for="assetId">Tài sản *</label><select class="form-control" id="assetId" name="assetId" required><option value="">Chọn tài sản</option><c:forEach items="${quantityAssets}" var="a"><option value="${a.assetId}" ${param.assetId == a.assetId ? 'selected' : ''}><c:out value="${a.assetCode}"/> - <c:out value="${a.assetName}"/> (${a.totalQuantity})</option></c:forEach></select></div><div class="form-group"><label for="quantityReasonCode">Loại lý do *</label><select class="form-control" id="quantityReasonCode" name="reasonCode" required><option value="NOT_REPAIRABLE">Không thể sửa chữa</option><option value="UNSAFE">Không an toàn</option><option value="OBSOLETE">Lỗi thời</option><option value="REPAIR_NOT_ECONOMICAL">Sửa chữa không kinh tế</option><option value="OTHER">Khác</option></select></div><div class="form-group full-width"><label for="quantityReason">Chi tiết lý do *</label><textarea class="form-control" id="quantityReason" name="reason" required maxlength="1000"><c:out value="${param.reason}"/></textarea></div><div class="form-group full-width"><button class="primary-button" type="submit">Gửi yêu cầu</button></div></form></article></c:if>
            <c:if test="${not empty assetItems}"><article class="panel"><header class="panel-header"><div class="panel-title"><h3>Thiết bị có mã định danh</h3></div></header><form class="form-grid" method="post"><input type="hidden" name="csrfToken" value="${csrfToken}"><input type="hidden" name="action" value="create"><div class="form-group full-width"><label for="assetItemId">Thiết bị *</label><select class="form-control" id="assetItemId" name="assetItemId" required><option value="">Chọn thiết bị</option><c:forEach items="${assetItems}" var="item"><option value="${item.assetItemId}" ${param.assetItemId == item.assetItemId ? 'selected' : ''}><c:out value="${item.itemTag}"/> - <c:out value="${item.assetName}"/> (<c:out value="${item.condition}"/>)</option></c:forEach></select></div><div class="form-group"><label for="reasonCode">Loại lý do *</label><select class="form-control" id="reasonCode" name="reasonCode" required><option value="NOT_REPAIRABLE">Không thể sửa chữa</option><option value="UNSAFE">Không an toàn</option><option value="OBSOLETE">Lỗi thời</option><option value="REPAIR_NOT_ECONOMICAL">Sửa chữa không kinh tế</option><option value="OTHER">Khác</option></select></div><div class="form-group full-width"><label for="itemReason">Chi tiết lý do *</label><textarea class="form-control" id="itemReason" name="reason" required maxlength="1000"><c:out value="${param.reason}"/></textarea></div><div class="form-group full-width"><button class="primary-button" type="submit">Gửi yêu cầu</button></div></form></article></c:if>
        </section>
    </main>
</div>
</body>
</html>
