<%@ page contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@ taglib prefix="c" uri="jakarta.tags.core"%>
<%@ taglib prefix="app" uri="/WEB-INF/app.tld"%>
<!DOCTYPE html>
<html lang="vi">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>Danh sách thực tập sinh #${internList.requestId} | LAB Asset</title><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-dashboard.css"><link rel="stylesheet" href="${pageContext.request.contextPath}/assets/css/mentor-intern-lists.css"></head>
<body class="mentor-page">
<div class="app-shell"><c:set var="activeMenu" value="internLists"/><%@ include file="../includes/sidebar.jspf"%><main class="main-content">
    <header class="topbar"><div class="heading-wrap"><button class="menu-button" id="menuButton" type="button" aria-label="Mở thanh điều hướng" aria-controls="sidebar" aria-expanded="false"><svg><use href="#i-menu"/></svg></button><div><h1>Danh sách thực tập sinh #<c:out value="${internList.requestId}"/></h1><p>Danh sách thực tập sinh theo học kỳ</p></div></div></header>
    <section class="request-page"><div class="page-title-row"><div><h2><c:out value="${internList.groupName}"/></h2><p><c:out value="${internList.semesterCode}"/> — <c:out value="${internList.semesterName}"/></p></div><div class="row-actions"><a class="secondary-button" href="${pageContext.request.contextPath}/mentor/interns">Quay lại</a><c:if test="${internList.status == 'PENDING'}"><a class="primary-button" href="${pageContext.request.contextPath}/mentor/interns/edit?id=${internList.requestId}">Sửa danh sách</a></c:if></div></div>
        <c:if test="${param.created == '1'}"><div class="notice">Đã gửi danh sách thực tập sinh.</div></c:if><c:if test="${param.updated == '1'}"><div class="notice">Đã cập nhật danh sách thực tập sinh.</div></c:if>
        <div class="detail-grid"><div class="detail-item"><span>Trạng thái</span><strong><span class="request-status status-${internList.status}"><c:out value="${app:label(internList.status)}"/></span></strong></div><div class="detail-item"><span>Học kỳ</span><strong><c:out value="${internList.semesterCode}"/></strong></div><div class="detail-item"><span>Thực tập sinh</span><strong><c:out value="${internList.studentCount}"/></strong></div><div class="detail-item"><span>Ngày gửi</span><strong><c:out value="${app:dateTime(internList.createdAt)}"/></strong></div></div>
        <section class="request-card detail-section"><header class="panel-header"><div class="panel-title"><span class="title-icon"><svg><use href="#i-users"/></svg></span><h3>Danh sách thực tập sinh</h3></div></header><div class="request-table-wrap"><table class="detail-table"><thead><tr><th>#</th><th>Mã thực tập sinh</th><th>Họ và tên</th><th>Địa chỉ email</th><th>Khóa</th></tr></thead><tbody><c:forEach var="intern" items="${internList.students}" varStatus="loop"><tr><td>${loop.count}</td><td><c:out value="${intern.studentCode}"/></td><td><c:out value="${intern.fullName}"/></td><td><c:out value="${intern.email}"/></td><td><c:out value="${intern.cohort}"/></td></tr></c:forEach></tbody></table></div></section>
        <div class="approval-note"><h3>Ghi chú của người hướng dẫn</h3><p><c:out value="${internList.requestNote}" default="Không có ghi chú."/></p></div><c:if test="${internList.status != 'PENDING'}"><div class="approval-note"><h3>Ghi chú quyết định của quản trị viên</h3><p><c:out value="${internList.approvalNote}" default="Không có ghi chú quyết định."/></p></div></c:if>
    </section>
</main></div>
</body></html>
